// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"log/slog"
	"suika/internal/biz"
	"suika/internal/conf"
	"suika/internal/data"
	"suika/internal/server"
	"suika/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, recorder *conf.Recorder, logger *slog.Logger) (*kratos.App, func(), error) {
	roomRegistry := biz.NewRoomRegistry(recorder)
	dataData, cleanup, err := data.NewData(confData, recorder)
	if err != nil {
		return nil, nil, err
	}
	recorderRepo := data.NewRecorderRepo(dataData, recorder)
	sessionStatsRepo := data.NewSessionStatsRepo(recorderRepo)
	roomUsecase := biz.NewRoomUsecase(roomRegistry, sessionStatsRepo)
	roomService := service.NewRoomService(roomUsecase)
	grpcServer := server.NewGRPCServer(confServer, roomService)
	httpServer := server.NewHTTPServer(confServer, roomService)
	liveClient := data.NewLiveClient(dataData)
	recorderUsecase := biz.NewRecorderUsecase(recorder, roomRegistry, recorderRepo, liveClient)
	recorderJob := server.NewRecorderJob(recorderUsecase)
	app := newApp(logger, grpcServer, httpServer, recorderJob)
	return app, func() {
		cleanup()
	}, nil
}
