// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"log/slog"
	"suika/internal/biz"
	"suika/internal/conf"
	"suika/internal/data"
	"suika/internal/server"
	"suika/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp 初始化 Kratos 应用。
func wireApp(confServer *conf.Server, confData *conf.Data, recorder *conf.Recorder, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, recorder)
	if err != nil {
		return nil, nil, err
	}
	roomRepo := data.NewRoomRepo(dataData)
	roomRegistry, err := biz.NewRoomRegistry(roomRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	recorderRepo := data.NewRecorderRepo(dataData, recorder)
	sessionStatsRepo := data.NewSessionStatsRepo(recorderRepo)
	roomUsecase := biz.NewRoomUsecase(roomRepo, roomRegistry, sessionStatsRepo)
	roomService := service.NewRoomService(roomUsecase)
	passportClient := data.NewPassportClient(dataData)
	credentialRepo := data.NewCredentialRepo(dataData)
	accountUsecase := biz.NewAccountUsecase(passportClient, credentialRepo)
	accountService := service.NewAccountService(accountUsecase)
	grpcServer := server.NewGRPCServer(confServer, roomService, accountService)
	httpServer := server.NewHTTPServer(confServer, roomService, accountService)
	liveClient := data.NewLiveClient(dataData)
	recorderUsecase := biz.NewRecorderUsecase(recorder, roomRegistry, recorderRepo, liveClient)
	daemon := server.NewDaemon(recorderUsecase)
	app := newApp(logger, grpcServer, httpServer, daemon)
	return app, func() {
		cleanup()
	}, nil
}
