// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: account/v1/account.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QRLoginStatus 扫码登录的轮询状态。
type QRLoginStatus int32

const (
	QRLoginStatus_QR_LOGIN_STATUS_UNSPECIFIED QRLoginStatus = 0
	// 尚未扫码。
	QRLoginStatus_QR_LOGIN_STATUS_NOT_SCANNED QRLoginStatus = 1
	// 已扫码、待手机端确认。
	QRLoginStatus_QR_LOGIN_STATUS_SCANNED QRLoginStatus = 2
	// 二维码已过期。
	QRLoginStatus_QR_LOGIN_STATUS_EXPIRED QRLoginStatus = 3
	// 确认成功，凭据已保存。
	QRLoginStatus_QR_LOGIN_STATUS_CONFIRMED QRLoginStatus = 4
)

// Enum value maps for QRLoginStatus.
var (
	QRLoginStatus_name = map[int32]string{
		0: "QR_LOGIN_STATUS_UNSPECIFIED",
		1: "QR_LOGIN_STATUS_NOT_SCANNED",
		2: "QR_LOGIN_STATUS_SCANNED",
		3: "QR_LOGIN_STATUS_EXPIRED",
		4: "QR_LOGIN_STATUS_CONFIRMED",
	}
	QRLoginStatus_value = map[string]int32{
		"QR_LOGIN_STATUS_UNSPECIFIED": 0,
		"QR_LOGIN_STATUS_NOT_SCANNED": 1,
		"QR_LOGIN_STATUS_SCANNED":     2,
		"QR_LOGIN_STATUS_EXPIRED":     3,
		"QR_LOGIN_STATUS_CONFIRMED":   4,
	}
)

func (x QRLoginStatus) Enum() *QRLoginStatus {
	p := new(QRLoginStatus)
	*p = x
	return p
}

func (x QRLoginStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QRLoginStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_account_v1_account_proto_enumTypes[0].Descriptor()
}

func (QRLoginStatus) Type() protoreflect.EnumType {
	return &file_account_v1_account_proto_enumTypes[0]
}

func (x QRLoginStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QRLoginStatus.Descriptor instead.
func (QRLoginStatus) EnumDescriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{0}
}

// AccountState 账号登录状态。
type AccountState int32

const (
	AccountState_ACCOUNT_STATE_UNSPECIFIED AccountState = 0
	// 数据库中没有凭据。
	AccountState_ACCOUNT_STATE_LOGGED_OUT AccountState = 1
	// 有凭据且 B 站确认在线。
	AccountState_ACCOUNT_STATE_LOGGED_IN AccountState = 2
	// 有凭据但 B 站报告未登录（凭据失效），需要重新扫码。
	AccountState_ACCOUNT_STATE_EXPIRED AccountState = 3
)

// Enum value maps for AccountState.
var (
	AccountState_name = map[int32]string{
		0: "ACCOUNT_STATE_UNSPECIFIED",
		1: "ACCOUNT_STATE_LOGGED_OUT",
		2: "ACCOUNT_STATE_LOGGED_IN",
		3: "ACCOUNT_STATE_EXPIRED",
	}
	AccountState_value = map[string]int32{
		"ACCOUNT_STATE_UNSPECIFIED": 0,
		"ACCOUNT_STATE_LOGGED_OUT":  1,
		"ACCOUNT_STATE_LOGGED_IN":   2,
		"ACCOUNT_STATE_EXPIRED":     3,
	}
)

func (x AccountState) Enum() *AccountState {
	p := new(AccountState)
	*p = x
	return p
}

func (x AccountState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountState) Descriptor() protoreflect.EnumDescriptor {
	return file_account_v1_account_proto_enumTypes[1].Descriptor()
}

func (AccountState) Type() protoreflect.EnumType {
	return &file_account_v1_account_proto_enumTypes[1]
}

func (x AccountState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountState.Descriptor instead.
func (AccountState) EnumDescriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{1}
}

// AccountInfo 账号登录信息。
type AccountInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State AccountState           `protobuf:"varint,1,opt,name=state,proto3,enum=account.v1.AccountState" json:"state,omitempty"`
	// 登录账号的昵称；未登录时为空。
	Uname string `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	// 登录账号的 mid；未登录时为 0。
	Mid           int64 `protobuf:"varint,3,opt,name=mid,proto3" json:"mid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	mi := &file_account_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountInfo) GetState() AccountState {
	if x != nil {
		return x.State
	}
	return AccountState_ACCOUNT_STATE_UNSPECIFIED
}

func (x *AccountInfo) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *AccountInfo) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

type CreateQRLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQRLoginRequest) Reset() {
	*x = CreateQRLoginRequest{}
	mi := &file_account_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQRLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQRLoginRequest) ProtoMessage() {}

func (x *CreateQRLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQRLoginRequest.ProtoReflect.Descriptor instead.
func (*CreateQRLoginRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{1}
}

type CreateQRLoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 二维码内容（URL），客户端渲染为二维码供 B 站 App 扫描。
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// 轮询凭证。
	QrcodeKey string `protobuf:"bytes,2,opt,name=qrcode_key,json=qrcodeKey,proto3" json:"qrcode_key,omitempty"`
	// 二维码失效时刻（生成时刻 + 180 秒）。
	ExpireTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQRLoginResponse) Reset() {
	*x = CreateQRLoginResponse{}
	mi := &file_account_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQRLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQRLoginResponse) ProtoMessage() {}

func (x *CreateQRLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQRLoginResponse.ProtoReflect.Descriptor instead.
func (*CreateQRLoginResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *CreateQRLoginResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateQRLoginResponse) GetQrcodeKey() string {
	if x != nil {
		return x.QrcodeKey
	}
	return ""
}

func (x *CreateQRLoginResponse) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

type PollQRLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QrcodeKey     string                 `protobuf:"bytes,1,opt,name=qrcode_key,json=qrcodeKey,proto3" json:"qrcode_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollQRLoginRequest) Reset() {
	*x = PollQRLoginRequest{}
	mi := &file_account_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollQRLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollQRLoginRequest) ProtoMessage() {}

func (x *PollQRLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollQRLoginRequest.ProtoReflect.Descriptor instead.
func (*PollQRLoginRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *PollQRLoginRequest) GetQrcodeKey() string {
	if x != nil {
		return x.QrcodeKey
	}
	return ""
}

type PollQRLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        QRLoginStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=account.v1.QRLoginStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollQRLoginResponse) Reset() {
	*x = PollQRLoginResponse{}
	mi := &file_account_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollQRLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollQRLoginResponse) ProtoMessage() {}

func (x *PollQRLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollQRLoginResponse.ProtoReflect.Descriptor instead.
func (*PollQRLoginResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *PollQRLoginResponse) GetStatus() QRLoginStatus {
	if x != nil {
		return x.Status
	}
	return QRLoginStatus_QR_LOGIN_STATUS_UNSPECIFIED
}

type GetAccountStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountStatusRequest) Reset() {
	*x = GetAccountStatusRequest{}
	mi := &file_account_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountStatusRequest) ProtoMessage() {}

func (x *GetAccountStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAccountStatusRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{5}
}

type GetAccountStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountInfo           `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountStatusResponse) Reset() {
	*x = GetAccountStatusResponse{}
	mi := &file_account_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountStatusResponse) ProtoMessage() {}

func (x *GetAccountStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAccountStatusResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountStatusResponse) GetAccount() *AccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_account_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{7}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_account_v1_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{8}
}

func (x *LogoutResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

var File_account_v1_account_proto protoreflect.FileDescriptor

const file_account_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x18account/v1/account.proto\x12\n" +
	"account.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"t\n" +
	"\vAccountInfo\x123\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.account.v1.AccountStateB\x03\xe0A\x03R\x05state\x12\x19\n" +
	"\x05uname\x18\x02 \x01(\tB\x03\xe0A\x03R\x05uname\x12\x15\n" +
	"\x03mid\x18\x03 \x01(\x03B\x03\xe0A\x03R\x03mid\"\x16\n" +
	"\x14CreateQRLoginRequest\"\x94\x01\n" +
	"\x15CreateQRLoginResponse\x12\x15\n" +
	"\x03url\x18\x01 \x01(\tB\x03\xe0A\x03R\x03url\x12\"\n" +
	"\n" +
	"qrcode_key\x18\x02 \x01(\tB\x03\xe0A\x03R\tqrcodeKey\x12@\n" +
	"\vexpire_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"expireTime\"8\n" +
	"\x12PollQRLoginRequest\x12\"\n" +
	"\n" +
	"qrcode_key\x18\x01 \x01(\tB\x03\xe0A\x02R\tqrcodeKey\"M\n" +
	"\x13PollQRLoginResponse\x126\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.account.v1.QRLoginStatusB\x03\xe0A\x03R\x06status\"\x19\n" +
	"\x17GetAccountStatusRequest\"R\n" +
	"\x18GetAccountStatusResponse\x126\n" +
	"\aaccount\x18\x01 \x01(\v2\x17.account.v1.AccountInfoB\x03\xe0A\x03R\aaccount\"\x0f\n" +
	"\rLogoutRequest\">\n" +
	"\x0eLogoutResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty*\xaa\x01\n" +
	"\rQRLoginStatus\x12\x1f\n" +
	"\x1bQR_LOGIN_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bQR_LOGIN_STATUS_NOT_SCANNED\x10\x01\x12\x1b\n" +
	"\x17QR_LOGIN_STATUS_SCANNED\x10\x02\x12\x1b\n" +
	"\x17QR_LOGIN_STATUS_EXPIRED\x10\x03\x12\x1d\n" +
	"\x19QR_LOGIN_STATUS_CONFIRMED\x10\x04*\x83\x01\n" +
	"\fAccountState\x12\x1d\n" +
	"\x19ACCOUNT_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ACCOUNT_STATE_LOGGED_OUT\x10\x01\x12\x1b\n" +
	"\x17ACCOUNT_STATE_LOGGED_IN\x10\x02\x12\x19\n" +
	"\x15ACCOUNT_STATE_EXPIRED\x10\x032\xe7\x03\n" +
	"\x0eAccountService\x12|\n" +
	"\rCreateQRLogin\x12 .account.v1.CreateQRLoginRequest\x1a!.account.v1.CreateQRLoginResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/account/qr-login/create\x12t\n" +
	"\vPollQRLogin\x12\x1e.account.v1.PollQRLoginRequest\x1a\x1f.account.v1.PollQRLoginResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/account/qr-login/poll\x12\x80\x01\n" +
	"\x10GetAccountStatus\x12#.account.v1.GetAccountStatusRequest\x1a$.account.v1.GetAccountStatusResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/account/status/get\x12^\n" +
	"\x06Logout\x12\x19.account.v1.LogoutRequest\x1a\x1a.account.v1.LogoutResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/account/logoutB6\n" +
	"\n" +
	"account.v1P\x01Z\x17suika/api/account/v1;v1\xa2\x02\fAPIAccountV1b\x06proto3"

var (
	file_account_v1_account_proto_rawDescOnce sync.Once
	file_account_v1_account_proto_rawDescData []byte
)

func file_account_v1_account_proto_rawDescGZIP() []byte {
	file_account_v1_account_proto_rawDescOnce.Do(func() {
		file_account_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v1_account_proto_rawDesc), len(file_account_v1_account_proto_rawDesc)))
	})
	return file_account_v1_account_proto_rawDescData
}

var file_account_v1_account_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_account_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_account_v1_account_proto_goTypes = []any{
	(QRLoginStatus)(0),               // 0: account.v1.QRLoginStatus
	(AccountState)(0),                // 1: account.v1.AccountState
	(*AccountInfo)(nil),              // 2: account.v1.AccountInfo
	(*CreateQRLoginRequest)(nil),     // 3: account.v1.CreateQRLoginRequest
	(*CreateQRLoginResponse)(nil),    // 4: account.v1.CreateQRLoginResponse
	(*PollQRLoginRequest)(nil),       // 5: account.v1.PollQRLoginRequest
	(*PollQRLoginResponse)(nil),      // 6: account.v1.PollQRLoginResponse
	(*GetAccountStatusRequest)(nil),  // 7: account.v1.GetAccountStatusRequest
	(*GetAccountStatusResponse)(nil), // 8: account.v1.GetAccountStatusResponse
	(*LogoutRequest)(nil),            // 9: account.v1.LogoutRequest
	(*LogoutResponse)(nil),           // 10: account.v1.LogoutResponse
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 12: google.protobuf.Empty
}
var file_account_v1_account_proto_depIdxs = []int32{
	1,  // 0: account.v1.AccountInfo.state:type_name -> account.v1.AccountState
	11, // 1: account.v1.CreateQRLoginResponse.expire_time:type_name -> google.protobuf.Timestamp
	0,  // 2: account.v1.PollQRLoginResponse.status:type_name -> account.v1.QRLoginStatus
	2,  // 3: account.v1.GetAccountStatusResponse.account:type_name -> account.v1.AccountInfo
	12, // 4: account.v1.LogoutResponse.empty:type_name -> google.protobuf.Empty
	3,  // 5: account.v1.AccountService.CreateQRLogin:input_type -> account.v1.CreateQRLoginRequest
	5,  // 6: account.v1.AccountService.PollQRLogin:input_type -> account.v1.PollQRLoginRequest
	7,  // 7: account.v1.AccountService.GetAccountStatus:input_type -> account.v1.GetAccountStatusRequest
	9,  // 8: account.v1.AccountService.Logout:input_type -> account.v1.LogoutRequest
	4,  // 9: account.v1.AccountService.CreateQRLogin:output_type -> account.v1.CreateQRLoginResponse
	6,  // 10: account.v1.AccountService.PollQRLogin:output_type -> account.v1.PollQRLoginResponse
	8,  // 11: account.v1.AccountService.GetAccountStatus:output_type -> account.v1.GetAccountStatusResponse
	10, // 12: account.v1.AccountService.Logout:output_type -> account.v1.LogoutResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_account_v1_account_proto_init() }
func file_account_v1_account_proto_init() {
	if File_account_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v1_account_proto_rawDesc), len(file_account_v1_account_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_v1_account_proto_goTypes,
		DependencyIndexes: file_account_v1_account_proto_depIdxs,
		EnumInfos:         file_account_v1_account_proto_enumTypes,
		MessageInfos:      file_account_v1_account_proto_msgTypes,
	}.Build()
	File_account_v1_account_proto = out.File
	file_account_v1_account_proto_goTypes = nil
	file_account_v1_account_proto_depIdxs = nil
}
