// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: account/v1/account.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationAccountServiceCreateQRLogin = "/account.v1.AccountService/CreateQRLogin"
const OperationAccountServiceGetAccountStatus = "/account.v1.AccountService/GetAccountStatus"
const OperationAccountServiceLogout = "/account.v1.AccountService/Logout"
const OperationAccountServicePollQRLogin = "/account.v1.AccountService/PollQRLogin"

type AccountServiceHTTPServer interface {
	// CreateQRLogin CreateQRLogin 生成扫码登录二维码（B 站侧有效期 180 秒）。
	CreateQRLogin(context.Context, *CreateQRLoginRequest) (*CreateQRLoginResponse, error)
	// GetAccountStatus GetAccountStatus 查询当前登录账号（以数据库凭据向 B 站核验）。
	GetAccountStatus(context.Context, *GetAccountStatusRequest) (*GetAccountStatusResponse, error)
	// Logout Logout 本地登出：删除数据库凭据并清除内存登录态，不调用 B 站登出接口。
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// PollQRLogin PollQRLogin 轮询扫码状态；确认成功时服务端持久化凭据并即时生效。
	PollQRLogin(context.Context, *PollQRLoginRequest) (*PollQRLoginResponse, error)
}

func RegisterAccountServiceHTTPServer(s *http.Server, srv AccountServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/account/qr-login/create", _AccountService_CreateQRLogin0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/account/qr-login/poll", _AccountService_PollQRLogin0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/account/status/get", _AccountService_GetAccountStatus0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/account/logout", _AccountService_Logout0_HTTP_Handler(srv))
}

func _AccountService_CreateQRLogin0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateQRLoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceCreateQRLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateQRLogin(ctx, req.(*CreateQRLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateQRLoginResponse)
		return ctx.Result(200, reply)
	}
}

func _AccountService_PollQRLogin0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PollQRLoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServicePollQRLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PollQRLogin(ctx, req.(*PollQRLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PollQRLoginResponse)
		return ctx.Result(200, reply)
	}
}

func _AccountService_GetAccountStatus0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAccountStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceGetAccountStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAccountStatus(ctx, req.(*GetAccountStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAccountStatusResponse)
		return ctx.Result(200, reply)
	}
}

func _AccountService_Logout0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogoutRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceLogout)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Logout(ctx, req.(*LogoutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LogoutResponse)
		return ctx.Result(200, reply)
	}
}

type AccountServiceHTTPClient interface {
	// CreateQRLogin CreateQRLogin 生成扫码登录二维码（B 站侧有效期 180 秒）。
	CreateQRLogin(ctx context.Context, req *CreateQRLoginRequest, opts ...http.CallOption) (rsp *CreateQRLoginResponse, err error)
	// GetAccountStatus GetAccountStatus 查询当前登录账号（以数据库凭据向 B 站核验）。
	GetAccountStatus(ctx context.Context, req *GetAccountStatusRequest, opts ...http.CallOption) (rsp *GetAccountStatusResponse, err error)
	// Logout Logout 本地登出：删除数据库凭据并清除内存登录态，不调用 B 站登出接口。
	Logout(ctx context.Context, req *LogoutRequest, opts ...http.CallOption) (rsp *LogoutResponse, err error)
	// PollQRLogin PollQRLogin 轮询扫码状态；确认成功时服务端持久化凭据并即时生效。
	PollQRLogin(ctx context.Context, req *PollQRLoginRequest, opts ...http.CallOption) (rsp *PollQRLoginResponse, err error)
}

type AccountServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAccountServiceHTTPClient(client *http.Client) AccountServiceHTTPClient {
	return &AccountServiceHTTPClientImpl{client}
}

// CreateQRLogin CreateQRLogin 生成扫码登录二维码（B 站侧有效期 180 秒）。
func (c *AccountServiceHTTPClientImpl) CreateQRLogin(ctx context.Context, in *CreateQRLoginRequest, opts ...http.CallOption) (*CreateQRLoginResponse, error) {
	var out CreateQRLoginResponse
	pattern := "/v1/account/qr-login/create"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAccountServiceCreateQRLogin),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAccountStatus GetAccountStatus 查询当前登录账号（以数据库凭据向 B 站核验）。
func (c *AccountServiceHTTPClientImpl) GetAccountStatus(ctx context.Context, in *GetAccountStatusRequest, opts ...http.CallOption) (*GetAccountStatusResponse, error) {
	var out GetAccountStatusResponse
	pattern := "/v1/account/status/get"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAccountServiceGetAccountStatus),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Logout Logout 本地登出：删除数据库凭据并清除内存登录态，不调用 B 站登出接口。
func (c *AccountServiceHTTPClientImpl) Logout(ctx context.Context, in *LogoutRequest, opts ...http.CallOption) (*LogoutResponse, error) {
	var out LogoutResponse
	pattern := "/v1/account/logout"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAccountServiceLogout),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PollQRLogin PollQRLogin 轮询扫码状态；确认成功时服务端持久化凭据并即时生效。
func (c *AccountServiceHTTPClientImpl) PollQRLogin(ctx context.Context, in *PollQRLoginRequest, opts ...http.CallOption) (*PollQRLoginResponse, error) {
	var out PollQRLoginResponse
	pattern := "/v1/account/qr-login/poll"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAccountServicePollQRLogin),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
