// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: account/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNSPECIFIED      ErrorReason = 0
	ErrorReason_ERROR_REASON_INTERNAL         ErrorReason = 1
	ErrorReason_ERROR_REASON_NOT_FOUND        ErrorReason = 2
	ErrorReason_ERROR_REASON_INVALID_ARGUMENT ErrorReason = 3
	ErrorReason_ERROR_REASON_ALREADY_EXISTS   ErrorReason = 4
	// 平台（B 站 passport/nav）不可用或拒绝请求，区别于服务自身故障。
	ErrorReason_ERROR_REASON_UNAVAILABLE ErrorReason = 5
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "ERROR_REASON_UNSPECIFIED",
		1: "ERROR_REASON_INTERNAL",
		2: "ERROR_REASON_NOT_FOUND",
		3: "ERROR_REASON_INVALID_ARGUMENT",
		4: "ERROR_REASON_ALREADY_EXISTS",
		5: "ERROR_REASON_UNAVAILABLE",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED":      0,
		"ERROR_REASON_INTERNAL":         1,
		"ERROR_REASON_NOT_FOUND":        2,
		"ERROR_REASON_INVALID_ARGUMENT": 3,
		"ERROR_REASON_ALREADY_EXISTS":   4,
		"ERROR_REASON_UNAVAILABLE":      5,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_account_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_account_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_account_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_account_v1_error_reason_proto protoreflect.FileDescriptor

const file_account_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1daccount/v1/error_reason.proto\x12\n" +
	"account.v1*\xc4\x01\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ERROR_REASON_INTERNAL\x10\x01\x12\x1a\n" +
	"\x16ERROR_REASON_NOT_FOUND\x10\x02\x12!\n" +
	"\x1dERROR_REASON_INVALID_ARGUMENT\x10\x03\x12\x1f\n" +
	"\x1bERROR_REASON_ALREADY_EXISTS\x10\x04\x12\x1c\n" +
	"\x18ERROR_REASON_UNAVAILABLE\x10\x05B6\n" +
	"\n" +
	"account.v1P\x01Z\x17suika/api/account/v1;v1\xa2\x02\fAPIAccountV1b\x06proto3"

var (
	file_account_v1_error_reason_proto_rawDescOnce sync.Once
	file_account_v1_error_reason_proto_rawDescData []byte
)

func file_account_v1_error_reason_proto_rawDescGZIP() []byte {
	file_account_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_account_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v1_error_reason_proto_rawDesc), len(file_account_v1_error_reason_proto_rawDesc)))
	})
	return file_account_v1_error_reason_proto_rawDescData
}

var file_account_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_account_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: account.v1.ErrorReason
}
var file_account_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_v1_error_reason_proto_init() }
func file_account_v1_error_reason_proto_init() {
	if File_account_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v1_error_reason_proto_rawDesc), len(file_account_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_account_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_account_v1_error_reason_proto_enumTypes,
	}.Build()
	File_account_v1_error_reason_proto = out.File
	file_account_v1_error_reason_proto_goTypes = nil
	file_account_v1_error_reason_proto_depIdxs = nil
}
