// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: room/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_ROOM_UNSPECIFIED ErrorReason = 0
	ErrorReason_ROOM_INTERNAL    ErrorReason = 1
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "ROOM_UNSPECIFIED",
		1: "ROOM_INTERNAL",
	}
	ErrorReason_value = map[string]int32{
		"ROOM_UNSPECIFIED": 0,
		"ROOM_INTERNAL":    1,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_room_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_room_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_room_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_room_v1_error_reason_proto protoreflect.FileDescriptor

const file_room_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1aroom/v1/error_reason.proto\x12\aroom.v1*6\n" +
	"\vErrorReason\x12\x14\n" +
	"\x10ROOM_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rROOM_INTERNAL\x10\x01B-\n" +
	"\aroom.v1P\x01Z\x14suika/api/room/v1;v1\xa2\x02\tAPIRoomV1b\x06proto3"

var (
	file_room_v1_error_reason_proto_rawDescOnce sync.Once
	file_room_v1_error_reason_proto_rawDescData []byte
)

func file_room_v1_error_reason_proto_rawDescGZIP() []byte {
	file_room_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_room_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_v1_error_reason_proto_rawDesc), len(file_room_v1_error_reason_proto_rawDesc)))
	})
	return file_room_v1_error_reason_proto_rawDescData
}

var file_room_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_room_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: room.v1.ErrorReason
}
var file_room_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_room_v1_error_reason_proto_init() }
func file_room_v1_error_reason_proto_init() {
	if File_room_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_v1_error_reason_proto_rawDesc), len(file_room_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_room_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_room_v1_error_reason_proto_enumTypes,
	}.Build()
	File_room_v1_error_reason_proto = out.File
	file_room_v1_error_reason_proto_goTypes = nil
	file_room_v1_error_reason_proto_depIdxs = nil
}
