// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: room/v1/room.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LiveStatus 表示房间的直播状态。
type LiveStatus int32

const (
	// 未指定直播状态。
	LiveStatus_LIVE_STATUS_UNSPECIFIED LiveStatus = 0
	// 房间未在直播。
	LiveStatus_LIVE_STATUS_PREPARING LiveStatus = 1
	// 房间正在直播。
	LiveStatus_LIVE_STATUS_LIVE LiveStatus = 2
)

// Enum value maps for LiveStatus.
var (
	LiveStatus_name = map[int32]string{
		0: "LIVE_STATUS_UNSPECIFIED",
		1: "LIVE_STATUS_PREPARING",
		2: "LIVE_STATUS_LIVE",
	}
	LiveStatus_value = map[string]int32{
		"LIVE_STATUS_UNSPECIFIED": 0,
		"LIVE_STATUS_PREPARING":   1,
		"LIVE_STATUS_LIVE":        2,
	}
)

func (x LiveStatus) Enum() *LiveStatus {
	p := new(LiveStatus)
	*p = x
	return p
}

func (x LiveStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiveStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_room_v1_room_proto_enumTypes[0].Descriptor()
}

func (LiveStatus) Type() protoreflect.EnumType {
	return &file_room_v1_room_proto_enumTypes[0]
}

func (x LiveStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiveStatus.Descriptor instead.
func (LiveStatus) EnumDescriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{0}
}

// RecordStatus 表示房间录制任务的状态。
type RecordStatus int32

const (
	// 未指定录制状态。
	RecordStatus_RECORD_STATUS_UNSPECIFIED RecordStatus = 0
	// 当前没有录制任务。
	RecordStatus_RECORD_STATUS_IDLE RecordStatus = 1
	// 正在录制直播流。
	RecordStatus_RECORD_STATUS_RECORDING RecordStatus = 2
	// 录制结束，正在合并文件。
	RecordStatus_RECORD_STATUS_REMUXING RecordStatus = 3
	// 录制任务发生错误。
	RecordStatus_RECORD_STATUS_ERROR RecordStatus = 4
)

// Enum value maps for RecordStatus.
var (
	RecordStatus_name = map[int32]string{
		0: "RECORD_STATUS_UNSPECIFIED",
		1: "RECORD_STATUS_IDLE",
		2: "RECORD_STATUS_RECORDING",
		3: "RECORD_STATUS_REMUXING",
		4: "RECORD_STATUS_ERROR",
	}
	RecordStatus_value = map[string]int32{
		"RECORD_STATUS_UNSPECIFIED": 0,
		"RECORD_STATUS_IDLE":        1,
		"RECORD_STATUS_RECORDING":   2,
		"RECORD_STATUS_REMUXING":    3,
		"RECORD_STATUS_ERROR":       4,
	}
)

func (x RecordStatus) Enum() *RecordStatus {
	p := new(RecordStatus)
	*p = x
	return p
}

func (x RecordStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_room_v1_room_proto_enumTypes[1].Descriptor()
}

func (RecordStatus) Type() protoreflect.EnumType {
	return &file_room_v1_room_proto_enumTypes[1]
}

func (x RecordStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordStatus.Descriptor instead.
func (RecordStatus) EnumDescriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{1}
}

type Room struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RoomId           int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RecordEnabled    bool                   `protobuf:"varint,3,opt,name=record_enabled,json=recordEnabled,proto3" json:"record_enabled,omitempty"`
	LiveStatus       LiveStatus             `protobuf:"varint,4,opt,name=live_status,json=liveStatus,proto3,enum=room.v1.LiveStatus" json:"live_status,omitempty"`
	RecordStatus     RecordStatus           `protobuf:"varint,5,opt,name=record_status,json=recordStatus,proto3,enum=room.v1.RecordStatus" json:"record_status,omitempty"`
	CurrentFile      string                 `protobuf:"bytes,6,opt,name=current_file,json=currentFile,proto3" json:"current_file,omitempty"`
	BytesWritten     int64                  `protobuf:"varint,7,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	SessionStartedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=session_started_at,json=sessionStartedAt,proto3" json:"session_started_at,omitempty"`
	LastError        string                 `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CreateTime       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	StreamerName     string                 `protobuf:"bytes,12,opt,name=streamer_name,json=streamerName,proto3" json:"streamer_name,omitempty"`
	RoomTitle        string                 `protobuf:"bytes,13,opt,name=room_title,json=roomTitle,proto3" json:"room_title,omitempty"`
	DownloadSpeedBps int64                  `protobuf:"varint,14,opt,name=download_speed_bps,json=downloadSpeedBps,proto3" json:"download_speed_bps,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_room_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Room) GetRecordEnabled() bool {
	if x != nil {
		return x.RecordEnabled
	}
	return false
}

func (x *Room) GetLiveStatus() LiveStatus {
	if x != nil {
		return x.LiveStatus
	}
	return LiveStatus_LIVE_STATUS_UNSPECIFIED
}

func (x *Room) GetRecordStatus() RecordStatus {
	if x != nil {
		return x.RecordStatus
	}
	return RecordStatus_RECORD_STATUS_UNSPECIFIED
}

func (x *Room) GetCurrentFile() string {
	if x != nil {
		return x.CurrentFile
	}
	return ""
}

func (x *Room) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *Room) GetSessionStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionStartedAt
	}
	return nil
}

func (x *Room) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Room) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Room) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Room) GetStreamerName() string {
	if x != nil {
		return x.StreamerName
	}
	return ""
}

func (x *Room) GetRoomTitle() string {
	if x != nil {
		return x.RoomTitle
	}
	return ""
}

func (x *Room) GetDownloadSpeedBps() int64 {
	if x != nil {
		return x.DownloadSpeedBps
	}
	return 0
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomRequest) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_room_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type GetRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	mi := &file_room_v1_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type ListRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	RoomId        *int64                 `protobuf:"varint,3,opt,name=room_id,json=roomId,proto3,oneof" json:"room_id,omitempty"`
	RecordEnabled *bool                  `protobuf:"varint,5,opt,name=record_enabled,json=recordEnabled,proto3,oneof" json:"record_enabled,omitempty"`
	StreamerName  *string                `protobuf:"bytes,6,opt,name=streamer_name,json=streamerName,proto3,oneof" json:"streamer_name,omitempty"`
	RoomTitle     *string                `protobuf:"bytes,7,opt,name=room_title,json=roomTitle,proto3,oneof" json:"room_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_room_v1_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{5}
}

func (x *ListRoomsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoomsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRoomsRequest) GetRoomId() int64 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

func (x *ListRoomsRequest) GetRecordEnabled() bool {
	if x != nil && x.RecordEnabled != nil {
		return *x.RecordEnabled
	}
	return false
}

func (x *ListRoomsRequest) GetStreamerName() string {
	if x != nil && x.StreamerName != nil {
		return *x.StreamerName
	}
	return ""
}

func (x *ListRoomsRequest) GetRoomTitle() string {
	if x != nil && x.RoomTitle != nil {
		return *x.RoomTitle
	}
	return ""
}

type ListRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_room_v1_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{6}
}

func (x *ListRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *ListRoomsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRoomRequest) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *UpdateRoomRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomResponse) Reset() {
	*x = UpdateRoomResponse{}
	mi := &file_room_v1_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomResponse) ProtoMessage() {}

func (x *UpdateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type DeleteRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomRequest) Reset() {
	*x = DeleteRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomRequest) ProtoMessage() {}

func (x *DeleteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type DeleteRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomResponse) Reset() {
	*x = DeleteRoomResponse{}
	mi := &file_room_v1_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomResponse) ProtoMessage() {}

func (x *DeleteRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRoomResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

var File_room_v1_room_proto protoreflect.FileDescriptor

const file_room_v1_room_proto_rawDesc = "" +
	"\n" +
	"\x12room/v1/room.proto\x12\aroom.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x05\n" +
	"\x04Room\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12%\n" +
	"\x0erecord_enabled\x18\x03 \x01(\bR\rrecordEnabled\x129\n" +
	"\vlive_status\x18\x04 \x01(\x0e2\x13.room.v1.LiveStatusB\x03\xe0A\x03R\n" +
	"liveStatus\x12?\n" +
	"\rrecord_status\x18\x05 \x01(\x0e2\x15.room.v1.RecordStatusB\x03\xe0A\x03R\frecordStatus\x12&\n" +
	"\fcurrent_file\x18\x06 \x01(\tB\x03\xe0A\x03R\vcurrentFile\x12(\n" +
	"\rbytes_written\x18\a \x01(\x03B\x03\xe0A\x03R\fbytesWritten\x12M\n" +
	"\x12session_started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\x10sessionStartedAt\x12\"\n" +
	"\n" +
	"last_error\x18\t \x01(\tB\x03\xe0A\x03R\tlastError\x12@\n" +
	"\vcreate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12(\n" +
	"\rstreamer_name\x18\f \x01(\tB\x03\xe0A\x03R\fstreamerName\x12\"\n" +
	"\n" +
	"room_title\x18\r \x01(\tB\x03\xe0A\x03R\troomTitle\x121\n" +
	"\x12download_speed_bps\x18\x0e \x01(\x03B\x03\xe0A\x03R\x10downloadSpeedBps\";\n" +
	"\x11CreateRoomRequest\x12&\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomB\x03\xe0A\x02R\x04room\"7\n" +
	"\x12CreateRoomResponse\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomR\x04room\".\n" +
	"\x0eGetRoomRequest\x12\x1c\n" +
	"\aroom_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06roomId\"4\n" +
	"\x0fGetRoomResponse\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomR\x04room\"\xa6\x02\n" +
	"\x10ListRoomsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1c\n" +
	"\aroom_id\x18\x03 \x01(\x03H\x00R\x06roomId\x88\x01\x01\x12*\n" +
	"\x0erecord_enabled\x18\x05 \x01(\bH\x01R\rrecordEnabled\x88\x01\x01\x12(\n" +
	"\rstreamer_name\x18\x06 \x01(\tH\x02R\fstreamerName\x88\x01\x01\x12\"\n" +
	"\n" +
	"room_title\x18\a \x01(\tH\x03R\troomTitle\x88\x01\x01B\n" +
	"\n" +
	"\b_room_idB\x11\n" +
	"\x0f_record_enabledB\x10\n" +
	"\x0e_streamer_nameB\r\n" +
	"\v_room_title\"`\n" +
	"\x11ListRoomsResponse\x12#\n" +
	"\x05rooms\x18\x01 \x03(\v2\r.room.v1.RoomR\x05rooms\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"}\n" +
	"\x11UpdateRoomRequest\x12&\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomB\x03\xe0A\x02R\x04room\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"7\n" +
	"\x12UpdateRoomResponse\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomR\x04room\"1\n" +
	"\x11DeleteRoomRequest\x12\x1c\n" +
	"\aroom_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06roomId\"B\n" +
	"\x12DeleteRoomResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty*Z\n" +
	"\n" +
	"LiveStatus\x12\x1b\n" +
	"\x17LIVE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LIVE_STATUS_PREPARING\x10\x01\x12\x14\n" +
	"\x10LIVE_STATUS_LIVE\x10\x02*\x97\x01\n" +
	"\fRecordStatus\x12\x1d\n" +
	"\x19RECORD_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RECORD_STATUS_IDLE\x10\x01\x12\x1b\n" +
	"\x17RECORD_STATUS_RECORDING\x10\x02\x12\x1a\n" +
	"\x16RECORD_STATUS_REMUXING\x10\x03\x12\x17\n" +
	"\x13RECORD_STATUS_ERROR\x10\x042\xf0\x03\n" +
	"\vRoomService\x12b\n" +
	"\n" +
	"CreateRoom\x12\x1a.room.v1.CreateRoomRequest\x1a\x1b.room.v1.CreateRoomResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/rooms/create\x12]\n" +
	"\tListRooms\x12\x19.room.v1.ListRoomsRequest\x1a\x1a.room.v1.ListRoomsResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/rooms/list\x12V\n" +
	"\aGetRoom\x12\x17.room.v1.GetRoomRequest\x1a\x18.room.v1.GetRoomResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/rooms/get\x12b\n" +
	"\n" +
	"UpdateRoom\x12\x1a.room.v1.UpdateRoomRequest\x1a\x1b.room.v1.UpdateRoomResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/rooms/update\x12b\n" +
	"\n" +
	"DeleteRoom\x12\x1a.room.v1.DeleteRoomRequest\x1a\x1b.room.v1.DeleteRoomResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/rooms/deleteB-\n" +
	"\aroom.v1P\x01Z\x14suika/api/room/v1;v1\xa2\x02\tAPIRoomV1b\x06proto3"

var (
	file_room_v1_room_proto_rawDescOnce sync.Once
	file_room_v1_room_proto_rawDescData []byte
)

func file_room_v1_room_proto_rawDescGZIP() []byte {
	file_room_v1_room_proto_rawDescOnce.Do(func() {
		file_room_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)))
	})
	return file_room_v1_room_proto_rawDescData
}

var file_room_v1_room_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_room_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_room_v1_room_proto_goTypes = []any{
	(LiveStatus)(0),               // 0: room.v1.LiveStatus
	(RecordStatus)(0),             // 1: room.v1.RecordStatus
	(*Room)(nil),                  // 2: room.v1.Room
	(*CreateRoomRequest)(nil),     // 3: room.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),    // 4: room.v1.CreateRoomResponse
	(*GetRoomRequest)(nil),        // 5: room.v1.GetRoomRequest
	(*GetRoomResponse)(nil),       // 6: room.v1.GetRoomResponse
	(*ListRoomsRequest)(nil),      // 7: room.v1.ListRoomsRequest
	(*ListRoomsResponse)(nil),     // 8: room.v1.ListRoomsResponse
	(*UpdateRoomRequest)(nil),     // 9: room.v1.UpdateRoomRequest
	(*UpdateRoomResponse)(nil),    // 10: room.v1.UpdateRoomResponse
	(*DeleteRoomRequest)(nil),     // 11: room.v1.DeleteRoomRequest
	(*DeleteRoomResponse)(nil),    // 12: room.v1.DeleteRoomResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 14: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_room_v1_room_proto_depIdxs = []int32{
	0,  // 0: room.v1.Room.live_status:type_name -> room.v1.LiveStatus
	1,  // 1: room.v1.Room.record_status:type_name -> room.v1.RecordStatus
	13, // 2: room.v1.Room.session_started_at:type_name -> google.protobuf.Timestamp
	13, // 3: room.v1.Room.create_time:type_name -> google.protobuf.Timestamp
	13, // 4: room.v1.Room.update_time:type_name -> google.protobuf.Timestamp
	2,  // 5: room.v1.CreateRoomRequest.room:type_name -> room.v1.Room
	2,  // 6: room.v1.CreateRoomResponse.room:type_name -> room.v1.Room
	2,  // 7: room.v1.GetRoomResponse.room:type_name -> room.v1.Room
	2,  // 8: room.v1.ListRoomsResponse.rooms:type_name -> room.v1.Room
	2,  // 9: room.v1.UpdateRoomRequest.room:type_name -> room.v1.Room
	14, // 10: room.v1.UpdateRoomRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 11: room.v1.UpdateRoomResponse.room:type_name -> room.v1.Room
	15, // 12: room.v1.DeleteRoomResponse.empty:type_name -> google.protobuf.Empty
	3,  // 13: room.v1.RoomService.CreateRoom:input_type -> room.v1.CreateRoomRequest
	7,  // 14: room.v1.RoomService.ListRooms:input_type -> room.v1.ListRoomsRequest
	5,  // 15: room.v1.RoomService.GetRoom:input_type -> room.v1.GetRoomRequest
	9,  // 16: room.v1.RoomService.UpdateRoom:input_type -> room.v1.UpdateRoomRequest
	11, // 17: room.v1.RoomService.DeleteRoom:input_type -> room.v1.DeleteRoomRequest
	4,  // 18: room.v1.RoomService.CreateRoom:output_type -> room.v1.CreateRoomResponse
	8,  // 19: room.v1.RoomService.ListRooms:output_type -> room.v1.ListRoomsResponse
	6,  // 20: room.v1.RoomService.GetRoom:output_type -> room.v1.GetRoomResponse
	10, // 21: room.v1.RoomService.UpdateRoom:output_type -> room.v1.UpdateRoomResponse
	12, // 22: room.v1.RoomService.DeleteRoom:output_type -> room.v1.DeleteRoomResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_room_v1_room_proto_init() }
func file_room_v1_room_proto_init() {
	if File_room_v1_room_proto != nil {
		return
	}
	file_room_v1_room_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_v1_room_proto_goTypes,
		DependencyIndexes: file_room_v1_room_proto_depIdxs,
		EnumInfos:         file_room_v1_room_proto_enumTypes,
		MessageInfos:      file_room_v1_room_proto_msgTypes,
	}.Build()
	File_room_v1_room_proto = out.File
	file_room_v1_room_proto_goTypes = nil
	file_room_v1_room_proto_depIdxs = nil
}
