// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: room/v1/room.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LiveStatus is the broadcast state of a room as reported by the platform.
type LiveStatus int32

const (
	LiveStatus_LIVE_STATUS_UNSPECIFIED LiveStatus = 0
	// PREPARING means the room is offline (not streaming).
	LiveStatus_PREPARING LiveStatus = 1
	// LIVE means the streamer is currently broadcasting.
	LiveStatus_LIVE LiveStatus = 2
)

// Enum value maps for LiveStatus.
var (
	LiveStatus_name = map[int32]string{
		0: "LIVE_STATUS_UNSPECIFIED",
		1: "PREPARING",
		2: "LIVE",
	}
	LiveStatus_value = map[string]int32{
		"LIVE_STATUS_UNSPECIFIED": 0,
		"PREPARING":               1,
		"LIVE":                    2,
	}
)

func (x LiveStatus) Enum() *LiveStatus {
	p := new(LiveStatus)
	*p = x
	return p
}

func (x LiveStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiveStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_room_v1_room_proto_enumTypes[0].Descriptor()
}

func (LiveStatus) Type() protoreflect.EnumType {
	return &file_room_v1_room_proto_enumTypes[0]
}

func (x LiveStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiveStatus.Descriptor instead.
func (LiveStatus) EnumDescriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{0}
}

// RecordStatus is the recorder's own state for a room.
type RecordStatus int32

const (
	RecordStatus_RECORD_STATUS_UNSPECIFIED RecordStatus = 0
	// IDLE means no recording session is active for the room.
	RecordStatus_IDLE RecordStatus = 1
	// RECORDING means a session is actively writing stream data.
	RecordStatus_RECORDING RecordStatus = 2
	// REMUXING means the session ended and segments are being remuxed.
	RecordStatus_REMUXING RecordStatus = 3
	// ERROR means the last operation for the room failed.
	RecordStatus_ERROR RecordStatus = 4
)

// Enum value maps for RecordStatus.
var (
	RecordStatus_name = map[int32]string{
		0: "RECORD_STATUS_UNSPECIFIED",
		1: "IDLE",
		2: "RECORDING",
		3: "REMUXING",
		4: "ERROR",
	}
	RecordStatus_value = map[string]int32{
		"RECORD_STATUS_UNSPECIFIED": 0,
		"IDLE":                      1,
		"RECORDING":                 2,
		"REMUXING":                  3,
		"ERROR":                     4,
	}
)

func (x RecordStatus) Enum() *RecordStatus {
	p := new(RecordStatus)
	*p = x
	return p
}

func (x RecordStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_room_v1_room_proto_enumTypes[1].Descriptor()
}

func (RecordStatus) Type() protoreflect.EnumType {
	return &file_room_v1_room_proto_enumTypes[1]
}

func (x RecordStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordStatus.Descriptor instead.
func (RecordStatus) EnumDescriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{1}
}

// Room is the canonical representation of one monitored room: persisted
// fields plus the runtime state merged in on read.
type Room struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Platform room id supplied by the caller. Serves as the unique
	// identifier; immutable once created.
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Streamer display name used for the recording directory. May be empty
	// on create; the recorder backfills it from the platform API.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Whether this room is monitored at all.
	Enabled bool `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Broadcast state reported by the platform. Runtime state, server-populated.
	LiveStatus LiveStatus `protobuf:"varint,4,opt,name=live_status,json=liveStatus,proto3,enum=room.v1.LiveStatus" json:"live_status,omitempty"`
	// Recorder state for this room. Runtime state, server-populated.
	RecordStatus RecordStatus `protobuf:"varint,5,opt,name=record_status,json=recordStatus,proto3,enum=room.v1.RecordStatus" json:"record_status,omitempty"`
	// Path of the segment file currently being written. Empty when idle.
	// Runtime state, server-populated.
	CurrentFile string `protobuf:"bytes,6,opt,name=current_file,json=currentFile,proto3" json:"current_file,omitempty"`
	// Bytes written across the current session. Zero when idle.
	// Runtime state, server-populated.
	BytesWritten int64 `protobuf:"varint,7,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	// Time at which the current session started. Absent when idle.
	// Runtime state, server-populated.
	SessionStartedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=session_started_at,json=sessionStartedAt,proto3" json:"session_started_at,omitempty"`
	// Last error observed for this room. Empty when healthy.
	// Runtime state, server-populated.
	LastError string `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// Time at which the room was registered. Server-assigned, read-only.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Time at which the room was last modified. Server-assigned, read-only.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_room_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Room) GetLiveStatus() LiveStatus {
	if x != nil {
		return x.LiveStatus
	}
	return LiveStatus_LIVE_STATUS_UNSPECIFIED
}

func (x *Room) GetRecordStatus() RecordStatus {
	if x != nil {
		return x.RecordStatus
	}
	return RecordStatus_RECORD_STATUS_UNSPECIFIED
}

func (x *Room) GetCurrentFile() string {
	if x != nil {
		return x.CurrentFile
	}
	return ""
}

func (x *Room) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *Room) GetSessionStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionStartedAt
	}
	return nil
}

func (x *Room) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Room) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Room) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// RoomSet is a paginated collection of rooms returned by ListRooms.
type RoomSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The page of rooms in the order requested by ListRoomsRequest.order_by.
	Rooms []*Room `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	// Token used to retrieve the next page via ListRoomsRequest.page_token.
	// Empty when there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomSet) Reset() {
	*x = RoomSet{}
	mi := &file_room_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSet) ProtoMessage() {}

func (x *RoomSet) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSet.ProtoReflect.Descriptor instead.
func (*RoomSet) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *RoomSet) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *RoomSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// CreateRoomRequest is the input for RoomService.CreateRoom.
type CreateRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The room to register. room_id must be the platform room id; the
	// create_time, update_time, and runtime fields are ignored on input and
	// populated by the server in the response.
	Room          *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomRequest) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// GetRoomRequest is the input for RoomService.GetRoom.
type GetRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Platform room id of the room to retrieve.
	RoomId        int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// ListRoomsRequest is the input for RoomService.ListRooms.
type ListRoomsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Maximum number of rooms to return in a single page.
	// The server applies a default of 20 when unset or out of range.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. Token from a previous response's next_page_token used to fetch
	// the next page. Leave empty to request the first page.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. The standard list filter. Only persisted fields are
	// supported; runtime fields are server-populated and not filterable.
	// Supported fields:
	//   - `room_id` (i.e. `room_id=123`)
	//   - `name` (i.e. `name:"streamer"`)
	//   - `enabled` (i.e. `enabled` or `NOT enabled`)
	//   - `create_time` range (i.e. `create_time>="2026-01-01T00:00:00Z"`)
	//   - `update_time` range (i.e. `update_time>="2026-01-01T00:00:00Z"`)
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. A comma-separated list of fields to order by. Only persisted
	// fields are supported; runtime fields are not orderable.
	// Supported fields:
	//   - `room_id`
	//   - `name`
	//   - `enabled`
	//   - `create_time`
	//   - `update_time`
	//
	// Append ` desc` to a field for descending order, e.g. `create_time desc`.
	// Defaults to ascending order when no direction is supplied.
	OrderBy       string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_room_v1_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{4}
}

func (x *ListRoomsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoomsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRoomsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListRoomsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// UpdateRoomRequest is the input for RoomService.UpdateRoom.
type UpdateRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The room carrying the new field values. room.room_id identifies the
	// target record and must be set.
	Room *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	// Set of field paths in room to overwrite. Only `name` and `enabled` are
	// supported; fields not listed are left unchanged.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRoomRequest) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *UpdateRoomRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// DeleteRoomRequest is the input for RoomService.DeleteRoom.
type DeleteRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Platform room id of the room to delete.
	RoomId        int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomRequest) Reset() {
	*x = DeleteRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomRequest) ProtoMessage() {}

func (x *DeleteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

var File_room_v1_room_proto protoreflect.FileDescriptor

const file_room_v1_room_proto_rawDesc = "" +
	"\n" +
	"\x12room/v1/room.proto\x12\aroom.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x04\n" +
	"\x04Room\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x129\n" +
	"\vlive_status\x18\x04 \x01(\x0e2\x13.room.v1.LiveStatusB\x03\xe0A\x03R\n" +
	"liveStatus\x12?\n" +
	"\rrecord_status\x18\x05 \x01(\x0e2\x15.room.v1.RecordStatusB\x03\xe0A\x03R\frecordStatus\x12&\n" +
	"\fcurrent_file\x18\x06 \x01(\tB\x03\xe0A\x03R\vcurrentFile\x12(\n" +
	"\rbytes_written\x18\a \x01(\x03B\x03\xe0A\x03R\fbytesWritten\x12M\n" +
	"\x12session_started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\x10sessionStartedAt\x12\"\n" +
	"\n" +
	"last_error\x18\t \x01(\tB\x03\xe0A\x03R\tlastError\x12@\n" +
	"\vcreate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\"V\n" +
	"\aRoomSet\x12#\n" +
	"\x05rooms\x18\x01 \x03(\v2\r.room.v1.RoomR\x05rooms\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\";\n" +
	"\x11CreateRoomRequest\x12&\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomB\x03\xe0A\x02R\x04room\".\n" +
	"\x0eGetRoomRequest\x12\x1c\n" +
	"\aroom_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06roomId\"\x81\x01\n" +
	"\x10ListRoomsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"}\n" +
	"\x11UpdateRoomRequest\x12&\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomB\x03\xe0A\x02R\x04room\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"1\n" +
	"\x11DeleteRoomRequest\x12\x1c\n" +
	"\aroom_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06roomId*B\n" +
	"\n" +
	"LiveStatus\x12\x1b\n" +
	"\x17LIVE_STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tPREPARING\x10\x01\x12\b\n" +
	"\x04LIVE\x10\x02*_\n" +
	"\fRecordStatus\x12\x1d\n" +
	"\x19RECORD_STATUS_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04IDLE\x10\x01\x12\r\n" +
	"\tRECORDING\x10\x02\x12\f\n" +
	"\bREMUXING\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x042\xc0\x03\n" +
	"\vRoomService\x12W\n" +
	"\n" +
	"CreateRoom\x12\x1a.room.v1.CreateRoomRequest\x1a\r.room.v1.Room\"\x1e\x82\xd3\xe4\x93\x02\x18:\x04room\"\x10/v1/rooms/create\x12P\n" +
	"\tListRooms\x12\x19.room.v1.ListRoomsRequest\x1a\x10.room.v1.RoomSet\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/rooms/list\x12N\n" +
	"\aGetRoom\x12\x17.room.v1.GetRoomRequest\x1a\r.room.v1.Room\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/rooms/{room_id}\x12W\n" +
	"\n" +
	"UpdateRoom\x12\x1a.room.v1.UpdateRoomRequest\x1a\r.room.v1.Room\"\x1e\x82\xd3\xe4\x93\x02\x18:\x04room\x1a\x10/v1/rooms/update\x12]\n" +
	"\n" +
	"DeleteRoom\x12\x1a.room.v1.DeleteRoomRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/rooms/{room_id}B\x16Z\x14suika/api/room/v1;v1b\x06proto3"

var (
	file_room_v1_room_proto_rawDescOnce sync.Once
	file_room_v1_room_proto_rawDescData []byte
)

func file_room_v1_room_proto_rawDescGZIP() []byte {
	file_room_v1_room_proto_rawDescOnce.Do(func() {
		file_room_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)))
	})
	return file_room_v1_room_proto_rawDescData
}

var file_room_v1_room_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_room_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_room_v1_room_proto_goTypes = []any{
	(LiveStatus)(0),               // 0: room.v1.LiveStatus
	(RecordStatus)(0),             // 1: room.v1.RecordStatus
	(*Room)(nil),                  // 2: room.v1.Room
	(*RoomSet)(nil),               // 3: room.v1.RoomSet
	(*CreateRoomRequest)(nil),     // 4: room.v1.CreateRoomRequest
	(*GetRoomRequest)(nil),        // 5: room.v1.GetRoomRequest
	(*ListRoomsRequest)(nil),      // 6: room.v1.ListRoomsRequest
	(*UpdateRoomRequest)(nil),     // 7: room.v1.UpdateRoomRequest
	(*DeleteRoomRequest)(nil),     // 8: room.v1.DeleteRoomRequest
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 10: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_room_v1_room_proto_depIdxs = []int32{
	0,  // 0: room.v1.Room.live_status:type_name -> room.v1.LiveStatus
	1,  // 1: room.v1.Room.record_status:type_name -> room.v1.RecordStatus
	9,  // 2: room.v1.Room.session_started_at:type_name -> google.protobuf.Timestamp
	9,  // 3: room.v1.Room.create_time:type_name -> google.protobuf.Timestamp
	9,  // 4: room.v1.Room.update_time:type_name -> google.protobuf.Timestamp
	2,  // 5: room.v1.RoomSet.rooms:type_name -> room.v1.Room
	2,  // 6: room.v1.CreateRoomRequest.room:type_name -> room.v1.Room
	2,  // 7: room.v1.UpdateRoomRequest.room:type_name -> room.v1.Room
	10, // 8: room.v1.UpdateRoomRequest.update_mask:type_name -> google.protobuf.FieldMask
	4,  // 9: room.v1.RoomService.CreateRoom:input_type -> room.v1.CreateRoomRequest
	6,  // 10: room.v1.RoomService.ListRooms:input_type -> room.v1.ListRoomsRequest
	5,  // 11: room.v1.RoomService.GetRoom:input_type -> room.v1.GetRoomRequest
	7,  // 12: room.v1.RoomService.UpdateRoom:input_type -> room.v1.UpdateRoomRequest
	8,  // 13: room.v1.RoomService.DeleteRoom:input_type -> room.v1.DeleteRoomRequest
	2,  // 14: room.v1.RoomService.CreateRoom:output_type -> room.v1.Room
	3,  // 15: room.v1.RoomService.ListRooms:output_type -> room.v1.RoomSet
	2,  // 16: room.v1.RoomService.GetRoom:output_type -> room.v1.Room
	2,  // 17: room.v1.RoomService.UpdateRoom:output_type -> room.v1.Room
	11, // 18: room.v1.RoomService.DeleteRoom:output_type -> google.protobuf.Empty
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_room_v1_room_proto_init() }
func file_room_v1_room_proto_init() {
	if File_room_v1_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_v1_room_proto_goTypes,
		DependencyIndexes: file_room_v1_room_proto_depIdxs,
		EnumInfos:         file_room_v1_room_proto_enumTypes,
		MessageInfos:      file_room_v1_room_proto_msgTypes,
	}.Build()
	File_room_v1_room_proto = out.File
	file_room_v1_room_proto_goTypes = nil
	file_room_v1_room_proto_depIdxs = nil
}
