// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: room/v1/room.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LiveStatus is the broadcast state of a room as reported by Bilibili.
type LiveStatus int32

const (
	LiveStatus_LIVE_STATUS_UNSPECIFIED LiveStatus = 0
	// PREPARING means the room is offline (not streaming).
	LiveStatus_PREPARING LiveStatus = 1
	// LIVE means the streamer is currently broadcasting.
	LiveStatus_LIVE LiveStatus = 2
)

// Enum value maps for LiveStatus.
var (
	LiveStatus_name = map[int32]string{
		0: "LIVE_STATUS_UNSPECIFIED",
		1: "PREPARING",
		2: "LIVE",
	}
	LiveStatus_value = map[string]int32{
		"LIVE_STATUS_UNSPECIFIED": 0,
		"PREPARING":               1,
		"LIVE":                    2,
	}
)

func (x LiveStatus) Enum() *LiveStatus {
	p := new(LiveStatus)
	*p = x
	return p
}

func (x LiveStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiveStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_room_v1_room_proto_enumTypes[0].Descriptor()
}

func (LiveStatus) Type() protoreflect.EnumType {
	return &file_room_v1_room_proto_enumTypes[0]
}

func (x LiveStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiveStatus.Descriptor instead.
func (LiveStatus) EnumDescriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{0}
}

// RecordStatus is the recorder's own state for a room.
type RecordStatus int32

const (
	RecordStatus_RECORD_STATUS_UNSPECIFIED RecordStatus = 0
	// IDLE means no recording session is active for the room.
	RecordStatus_IDLE RecordStatus = 1
	// RECORDING means a session is actively writing stream data.
	RecordStatus_RECORDING RecordStatus = 2
	// REMUXING means the session ended and segments are being remuxed.
	RecordStatus_REMUXING RecordStatus = 3
	// ERROR means the last operation for the room failed.
	RecordStatus_ERROR RecordStatus = 4
)

// Enum value maps for RecordStatus.
var (
	RecordStatus_name = map[int32]string{
		0: "RECORD_STATUS_UNSPECIFIED",
		1: "IDLE",
		2: "RECORDING",
		3: "REMUXING",
		4: "ERROR",
	}
	RecordStatus_value = map[string]int32{
		"RECORD_STATUS_UNSPECIFIED": 0,
		"IDLE":                      1,
		"RECORDING":                 2,
		"REMUXING":                  3,
		"ERROR":                     4,
	}
)

func (x RecordStatus) Enum() *RecordStatus {
	p := new(RecordStatus)
	*p = x
	return p
}

func (x RecordStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_room_v1_room_proto_enumTypes[1].Descriptor()
}

func (RecordStatus) Type() protoreflect.EnumType {
	return &file_room_v1_room_proto_enumTypes[1]
}

func (x RecordStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordStatus.Descriptor instead.
func (RecordStatus) EnumDescriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{1}
}

// RoomStatus is the combined live/record status of one configured room.
type RoomStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bilibili room id.
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Streamer display name used for the recording directory.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Whether this room is monitored at all.
	Enabled bool `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Broadcast state reported by Bilibili.
	LiveStatus LiveStatus `protobuf:"varint,4,opt,name=live_status,json=liveStatus,proto3,enum=room.v1.LiveStatus" json:"live_status,omitempty"`
	// Recorder state for this room.
	RecordStatus RecordStatus `protobuf:"varint,5,opt,name=record_status,json=recordStatus,proto3,enum=room.v1.RecordStatus" json:"record_status,omitempty"`
	// Path of the segment file currently being written. Empty when idle.
	CurrentFile string `protobuf:"bytes,6,opt,name=current_file,json=currentFile,proto3" json:"current_file,omitempty"`
	// Bytes written across the current session. Zero when idle.
	BytesWritten int64 `protobuf:"varint,7,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	// Time at which the current session started. Absent when idle.
	SessionStartedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=session_started_at,json=sessionStartedAt,proto3" json:"session_started_at,omitempty"`
	// Last error observed for this room. Empty when healthy.
	LastError     string `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomStatus) Reset() {
	*x = RoomStatus{}
	mi := &file_room_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStatus) ProtoMessage() {}

func (x *RoomStatus) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStatus.ProtoReflect.Descriptor instead.
func (*RoomStatus) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *RoomStatus) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RoomStatus) GetLiveStatus() LiveStatus {
	if x != nil {
		return x.LiveStatus
	}
	return LiveStatus_LIVE_STATUS_UNSPECIFIED
}

func (x *RoomStatus) GetRecordStatus() RecordStatus {
	if x != nil {
		return x.RecordStatus
	}
	return RecordStatus_RECORD_STATUS_UNSPECIFIED
}

func (x *RoomStatus) GetCurrentFile() string {
	if x != nil {
		return x.CurrentFile
	}
	return ""
}

func (x *RoomStatus) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *RoomStatus) GetSessionStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionStartedAt
	}
	return nil
}

func (x *RoomStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// ListRoomsRequest is the input for RoomService.ListRooms.
type ListRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_room_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{1}
}

// ListRoomsResponse is the output for RoomService.ListRooms.
type ListRoomsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of every configured room, in configuration order.
	Rooms         []*RoomStatus `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_room_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *ListRoomsResponse) GetRooms() []*RoomStatus {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_room_v1_room_proto protoreflect.FileDescriptor

const file_room_v1_room_proto_rawDesc = "" +
	"\n" +
	"\x12room/v1/room.proto\x12\aroom.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x02\n" +
	"\n" +
	"RoomStatus\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x124\n" +
	"\vlive_status\x18\x04 \x01(\x0e2\x13.room.v1.LiveStatusR\n" +
	"liveStatus\x12:\n" +
	"\rrecord_status\x18\x05 \x01(\x0e2\x15.room.v1.RecordStatusR\frecordStatus\x12!\n" +
	"\fcurrent_file\x18\x06 \x01(\tR\vcurrentFile\x12#\n" +
	"\rbytes_written\x18\a \x01(\x03R\fbytesWritten\x12H\n" +
	"\x12session_started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x10sessionStartedAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError\"\x12\n" +
	"\x10ListRoomsRequest\">\n" +
	"\x11ListRoomsResponse\x12)\n" +
	"\x05rooms\x18\x01 \x03(\v2\x13.room.v1.RoomStatusR\x05rooms*B\n" +
	"\n" +
	"LiveStatus\x12\x1b\n" +
	"\x17LIVE_STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tPREPARING\x10\x01\x12\b\n" +
	"\x04LIVE\x10\x02*_\n" +
	"\fRecordStatus\x12\x1d\n" +
	"\x19RECORD_STATUS_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04IDLE\x10\x01\x12\r\n" +
	"\tRECORDING\x10\x02\x12\f\n" +
	"\bREMUXING\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x042i\n" +
	"\vRoomService\x12Z\n" +
	"\tListRooms\x12\x19.room.v1.ListRoomsRequest\x1a\x1a.room.v1.ListRoomsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/rooms/listB\x16Z\x14suika/api/room/v1;v1b\x06proto3"

var (
	file_room_v1_room_proto_rawDescOnce sync.Once
	file_room_v1_room_proto_rawDescData []byte
)

func file_room_v1_room_proto_rawDescGZIP() []byte {
	file_room_v1_room_proto_rawDescOnce.Do(func() {
		file_room_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)))
	})
	return file_room_v1_room_proto_rawDescData
}

var file_room_v1_room_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_room_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_room_v1_room_proto_goTypes = []any{
	(LiveStatus)(0),               // 0: room.v1.LiveStatus
	(RecordStatus)(0),             // 1: room.v1.RecordStatus
	(*RoomStatus)(nil),            // 2: room.v1.RoomStatus
	(*ListRoomsRequest)(nil),      // 3: room.v1.ListRoomsRequest
	(*ListRoomsResponse)(nil),     // 4: room.v1.ListRoomsResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_room_v1_room_proto_depIdxs = []int32{
	0, // 0: room.v1.RoomStatus.live_status:type_name -> room.v1.LiveStatus
	1, // 1: room.v1.RoomStatus.record_status:type_name -> room.v1.RecordStatus
	5, // 2: room.v1.RoomStatus.session_started_at:type_name -> google.protobuf.Timestamp
	2, // 3: room.v1.ListRoomsResponse.rooms:type_name -> room.v1.RoomStatus
	3, // 4: room.v1.RoomService.ListRooms:input_type -> room.v1.ListRoomsRequest
	4, // 5: room.v1.RoomService.ListRooms:output_type -> room.v1.ListRoomsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_room_v1_room_proto_init() }
func file_room_v1_room_proto_init() {
	if File_room_v1_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_v1_room_proto_goTypes,
		DependencyIndexes: file_room_v1_room_proto_depIdxs,
		EnumInfos:         file_room_v1_room_proto_enumTypes,
		MessageInfos:      file_room_v1_room_proto_msgTypes,
	}.Build()
	File_room_v1_room_proto = out.File
	file_room_v1_room_proto_goTypes = nil
	file_room_v1_room_proto_depIdxs = nil
}
