// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: room/v1/room.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationRoomServiceListRooms = "/room.v1.RoomService/ListRooms"

type RoomServiceHTTPServer interface {
	// ListRooms ListRooms returns the live/record status of every configured room.
	// The room set is fixed by configuration, so no pagination is offered.
	ListRooms(context.Context, *ListRoomsRequest) (*ListRoomsResponse, error)
}

func RegisterRoomServiceHTTPServer(s *http.Server, srv RoomServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/rooms/list", _RoomService_ListRooms0_HTTP_Handler(srv))
}

func _RoomService_ListRooms0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRoomsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceListRooms)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRooms(ctx, req.(*ListRoomsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRoomsResponse)
		return ctx.Result(200, reply)
	}
}

type RoomServiceHTTPClient interface {
	// ListRooms ListRooms returns the live/record status of every configured room.
	// The room set is fixed by configuration, so no pagination is offered.
	ListRooms(ctx context.Context, req *ListRoomsRequest, opts ...http.CallOption) (rsp *ListRoomsResponse, err error)
}

type RoomServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRoomServiceHTTPClient(client *http.Client) RoomServiceHTTPClient {
	return &RoomServiceHTTPClientImpl{client}
}

// ListRooms ListRooms returns the live/record status of every configured room.
// The room set is fixed by configuration, so no pagination is offered.
func (c *RoomServiceHTTPClientImpl) ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...http.CallOption) (*ListRoomsResponse, error) {
	var out ListRoomsResponse
	pattern := "/v1/rooms/list"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationRoomServiceListRooms),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
